name: RobotFramework

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install firefox
        firefox --version
        apt-get unzip
        curl https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        unzip geckodriver-v0.34.0-linux64.tar.gz
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary
        robot -d ./output/ ./tc01.robot

