name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Firefox
      uses: actions/setup-firefox@v3

    - name: Install geckodriver
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: |
        pip install --upgrade pip
        pip install robotframework-seleniumlibrary
        geckodriver --version

    
