name: RobotFramework

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update dependencies
      run: |
        sudo apt-get update


    - name: Install Firefox & Geckodriver
      run: |
        sudo apt-get install firefox
        sudo firefox --version
        sudo apt update
        sudo apt upgrade
        sudo apt install unzip
        sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        sudo sh -c 'tar -x geckodriver -zf geckodriver-v0.34.0-linux64.tar.gz -O > /usr/bin/geckodriver'
        sudo chmod +x /usr/bin/geckodriver
        export PATH=$PATH:/usr/bin/geckodriver
        geckodriver --version
        ls -ltr
        pwd

    - name: Install Robot Framework and Selenium
      run: |    
        python3 -m pip install --upgrade pip==23.3.1
        pip install robotframework robotframework-seleniumlibrary robotframework-pabot
        
        
    - name: Run Robot Test
      run: |
        pabot -d .\output\ -i Test .
      # Define the artifacts to upload
      # The `output` directory will be uploaded as an artifact
      # after the tests have run
      # You can add more directories or files if needed
      # Use `*` for wildcard matching

      