name: RobotFramework

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install firefox
        sudo firefox --version
        sudo apt update
        sudo apt upgrade
        sudo apt install unzip
        sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        sudo tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
        sudo chmod +x geckodriver-v0.34.0-linux64
        sudo export PATH=$PATH:/geckodriver/
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary
        robot -d ./output/ ./tc01.robot

